import localFont from "next/font/local";
import "../../globals.css";

import Image from "next/image";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "welcome to CarePointStores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="lg:max-w-[calc(100%-335px)] md:w-[calc(100%-335px)] overflow-x-clip"> */}

        <div className="p-4 md:px-2 lg:px-16 pt-20">{children}</div>
      </body>
    </html>
  );
}
