// import localFont from "next/font/local";
import ProgressCheck from "@/app/components/CheckOut/ProgressCheck";
import "../../../globals.css";
// import Navbar from "../components/Navbar";
// import Footer from "../components/Footer";
import localFont from "next/font/local";
import SponsoredProducts from "@/app/components/SponsoredProducts";
import HeaderPath from "@/app/components/headerPath";


const geistSans = localFont({
  src: "../../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "welcome to CarePointStores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <div className="p-4 mt-8 md:mt-0 bg-schemes-light-background    pb-0 px-0 md:px-2 lg:px-0 min-h-svh  space-y-4">
        <HeaderPath/>
        <div className='row-span-1 bg-white'>
            <ProgressCheck/>
            </div>
        {children}
        <div className="">
        <SponsoredProducts/>
        </div>
        
        </div>
         
        
    
  );
}
