// import localFont from "next/font/local";
import "../globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { auth } from "@/auth";

// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "welcome to CarePointStores",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await auth();
  return (
    <div className={` grid grid-cols-1 grid-rows-1  antialiased`}>
      <Navbar user={user}/>

      {/* <div className="lg:max-w-[calc(100%-335px)] md:w-[calc(100%-335px)] overflow-x-clip"> */}

      <div className="p-4 pb-0 px-0 md:px-2 lg:px-0 pt-[6.5rem] min-h-screen  bg-schemes-light-surface">
        {children}
      </div>

      <Footer />
    </div>
  );
}
