import localFont from "next/font/local";
import "../globals.css";
import Navbar from "../components/Navbar";
import Image from "next/image";
import Footer from "../components/Footer";
import SideBar from "../components/SideBar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "welcome to CarePointStores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid`}
      >
      <div className="md:grid md:grid-cols-[320px_1fr] lg:grid-cols-[320px_1fr] gap-0">
      <div className="">
      <SideBar />
      </div>
        
        <div className="">
          {children}
          <Footer />
        </div>
        </div>
      </body>
    </html>
  );
}
