import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./storeProvider";
import { SessionProvider } from "next-auth/react";
import { ReactQueryClientProvider } from "./lib/queryClient/queryClient";
import ErrorBoundary from "./util/ErrorBoundary";
import FeedBack from "./components/FeedBack";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider baseUrl={"/api/auth"}>
        <StoreProvider>
          <ReactQueryClientProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased bg-schemes-light-background  text-schemes-light-onBackground`}
            >
              <FeedBack />
              <ErrorBoundary>{children}</ErrorBoundary>
            </body>
          </ReactQueryClientProvider>
        </StoreProvider>
      </SessionProvider>
    </html>
  );
}
