import localFont from "next/font/local";
import "../../globals.css";
import FooterPath from "@/app/components/FooterPath";
import SponsoredProducts from "@/app/components/SponsoredProducts";


const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "welcome to CarePointStores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
        
       <div className=" md:px-8 space-y-2 mb-2 bg-schemes-light-background">
        
        {children}
         <div className=" min-h-[200px] py-2  text-schemes-light-onSurface  bg-schemes-light-surface  rounded-[3px] flex flex-col space-y-4 px-2">
                      <h1 className="relative inline-block products">Similar Product</h1>
                      <SponsoredProducts />
                    </div>
        <div className="bg-schemes-light-surface  pb-2 py-4"> 
        <FooterPath/>
        </div>
        
        </div>
         
        
      
    
  );
}
