

import localFont from "next/font/local";
import "../../globals.css";


const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Log in",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
        <main className=" bg-schemes-light-background  text-schemes-light-onBackground  min-h-dvh grid  grid-cols-1 p-16">{children}</main>
      
      </div>
  );
}
