// import localFont from "next/font/local";
import "../globals.css";
import Footer from "../components/Footer";
import SettingsNav from "../components/settings/SettingsNav";

// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "welcome to CarePointStores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <div
        className={` grid grid-flow-row grid-rows-1`}
      >
     <div className=" row-span-1 z-50 full_index">
     <SettingsNav/>
     </div>
     
      
        
        {/* <div className="lg:max-w-[calc(100%-335px)] md:w-[calc(100%-335px)] overflow-x-clip"> */}
       
        <div className="p-4 min-h-[calc(100vh-200px)] mt-8 pt-8 pb-0 px-0 md:px-2 lg:px-0 row-span-2 bg-schemes-light-surface text-schemes-light-onBackground ">
        {children}
        </div>
         <div className=" row-span-3">
         <Footer />
         </div>
         
        
      </div>
  );
}
